sudo: required
language: java
jdk: openjdk8

services:
  - docker
  
env:
  global: 
  - secure: "encrypted-dockerhub-username"
  - secure: "encrypted-dockerhub-password"
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}
  
      
before_install:
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
 
script: 
  - ./mvnw clean install -B
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=crisda24/sersuarios
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - registry.heroku.com/$HEROKU_APP_NAME/usuarios
  
cache: 
  directories:
    - '$HOME/.m2/repository'
  
deploy:
  provider: script
  script:
    - docker push $IMAGE_NAME 
     registry.heroku.com/$HEROKU_APP_NAME/usuarios
  on: 
    branch: master
  